#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Summarise review/adversarial/results/* into markdown tables for the report.

Usage:  python make_report_tables.py
Writes: results/tables.md
"""
import collections
import csv
import json
import os

import numpy as np

BASE = os.path.dirname(os.path.abspath(__file__))
RES = os.path.join(BASE, "results")
OUT = []


def w(s=""):
    OUT.append(s)


def fmt(x, nd=3):
    try:
        x = float(x)
    except Exception:
        return str(x)
    if x == 0:
        return "0"
    if abs(x) < 1e-3 or abs(x) >= 1e4:
        return ("%%.%de" % nd) % x
    return ("%%.%df" % nd) % x


def load_csv(name):
    p = os.path.join(RES, name)
    if not os.path.exists(p):
        return []
    with open(p) as f:
        return list(csv.DictReader(f))


def agg(rows, key, val="err_inf"):
    d = collections.defaultdict(list)
    for r in rows:
        d[r[key]].append(float(r[val]))
    return d


def table_from(d, keyname, sort_key=None):
    keys = sorted(d, key=sort_key) if sort_key else sorted(d)
    w("| %s | n | max \\|bhat-bclaim\\|_inf | median |" % keyname)
    w("|---|---|---|---|")
    for k in keys:
        v = np.array(d[k])
        w("| %s | %d | %s | %s |" % (k, len(v), fmt(v.max()), fmt(np.median(v))))
    w("")


def main():
    summary = {}
    p = os.path.join(RES, "summary.json")
    if os.path.exists(p):
        summary = json.load(open(p))
    sweep = load_csv("config_table.csv")
    route2 = load_csv("route2_table.csv")
    mc = load_csv("mc_table.csv")

    w("# Numerical results (auto-generated from results/*.csv)")
    w("")
    w("Generated by `make_report_tables.py` from the raw output of")
    w("`adversarial_check.py`.")
    w("")

    # ---------------- machinery validation -------------------------------
    if "validation" in summary:
        w("## 1. Accuracy of the numerical machinery")
        w("")
        w("`|Xi err|`: table vs. fresh adaptive quadrature; `xrule`: density")
        w("quadrature rule vs. quadrature; `G err`: G-table vs. quadrature;")
        w("`MC check`: |Xi_table - Monte-Carlo estimate| (MC s.e. ~ 1e-3 at")
        w("n = 4e6, so this column can only confirm the table to ~3e-3).")
        w("")
        w("| eps | mean | sd | \\|Xi err\\| | x-rule err | G err | MC check |")
        w("|---|---|---|---|---|---|---|")
        for r in summary["validation"]:
            w("| %s | %s | %s | %s | %s | %s | %s |"
              % (r["eps"], fmt(r["mean"]), fmt(r["sd"]), fmt(r["xi_err"], 2),
                 fmt(r["xrule_err"], 2), fmt(r["gtable_err"], 2),
                 fmt(r["mc_err"], 2)))
        w("")
        w("max |Xi err| = %s, max x-rule err = %s, max G-table err = %s"
          % (fmt(summary.get("max_xi_err"), 2), fmt(summary.get("max_xrule_err"), 2),
             fmt(summary.get("max_gtable_err"), 2)))
        w("")
    if "route2_gh_convergence" in summary:
        w("### Route-2 Gauss-Hermite order convergence (p=1, su=0.25, laplace)")
        w("")
        w("| sigma | n_gh | F_route2 | F_route1 | diff |")
        w("|---|---|---|---|---|")
        for r in summary["route2_gh_convergence"]:
            w("| %g | %d | %.12f | %.12f | %s |"
              % (r["sigma"], r["n_gh"], r["F2"], r["F1"], fmt(r["diff"], 2)))
        w("")

    # ---------------- sweep ----------------------------------------------
    if sweep:
        w("## 2. Broad sweep (route 1): %d configurations" % len(sweep))
        w("")
        e = np.array([float(r["err_inf"]) for r in sweep])
        g = np.array([float(r["gap"]) for r in sweep])
        w("`err_inf` = max_j |beta_num_j - beta_claim_j|, `gap` = F(beta_num) - F(beta_claim) >= 0.")
        w("")
        w("- max err_inf = %s ; median = %s ; 99th pct = %s"
          % (fmt(e.max(), 2), fmt(np.median(e), 2), fmt(np.percentile(e, 99), 2)))
        w("- max gap = %s ; min gap = %s" % (fmt(g.max(), 2), fmt(g.min(), 2)))
        conf = [r for r in sweep if float(r["err_inf"]) < 1e-6]
        w("- configurations with err_inf < 1e-6: %d / %d" % (len(conf), len(sweep)))
        bad = [r for r in sweep if float(r["err_inf"]) >= 1e-6]
        w("- configurations with err_inf >= 1e-6: %d" % len(bad))
        if bad:
            cnt = collections.Counter(r["eps"] for r in bad)
            w("  (by error distribution: %s)" % dict(cnt))
            w("  NOTE: these are the *numerically flat* criteria (Xi(s) underflows")
            w("  to 0.0 in double precision); their gap is 0, i.e. the reported")
            w("  point has exactly the same objective value as the claim.")
        w("")
        table_from(agg(sweep, "block"), "block")
        table_from(agg(sweep, "eps"), "error distribution")
        table_from(agg(sweep, "tau"), "tau", sort_key=float)
        table_from(agg(sweep, "sigma"), "sigma (bandwidth)", sort_key=float)
        table_from(agg(sweep, "p"), "p", sort_key=float)

        # non-commuting / singular cases only
        nc = [r for r in sweep if float(r["comm_SxSu"]) > 1e-8 or float(r["comm_SxM"]) > 1e-8]
        if nc:
            v = np.array([float(r["err_inf"]) for r in nc])
            w("Configurations with NON-COMMUTING Sx/Su or Sx/M "
              "(||[A,B]||_F > 1e-8): n = %d, max err_inf = %s, median = %s"
              % (len(nc), fmt(v.max(), 2), fmt(np.median(v), 2)))
            w("")
        sing = [r for r in sweep if "rk=1" in r["Su"] or "rk=0" in r["Su"]
                or "rk=1" in r["M"] or "rk=0" in r["M"]]
        if sing:
            v = np.array([float(r["err_inf"]) for r in sing])
            w("Configurations with a SINGULAR Su or M (rank <= 1): n = %d, "
              "max err_inf = %s, median = %s"
              % (len(sing), fmt(v.max(), 2), fmt(np.median(v), 2)))
            w("")
        w("### 10 worst configurations")
        w("")
        w("| config | p | eps | sigma | err_inf | gap |")
        w("|---|---|---|---|---|---|")
        for r in sorted(sweep, key=lambda r: -float(r["err_inf"]))[:10]:
            w("| %s | %s | %s | %s | %s | %s |"
              % (r["name"], r["p"], r["eps"], r["sigma"], fmt(r["err_inf"], 2),
                 fmt(r["gap"], 2)))
        w("")
        if "worst_cfgs" in summary:
            pass

    # ---------------- route 2 --------------------------------------------
    if route2:
        w("## 3. Independent route 2 (direct Gauss-Hermite over the model)")
        w("")
        e2 = np.array([float(r["err_r2"]) for r in route2])
        df = np.array([abs(float(r["dF_r1_r2_claim"])) for r in route2])
        w("- %d configurations; max err_r2 = %s ; median = %s"
          % (len(route2), fmt(e2.max(), 2), fmt(np.median(e2), 2)))
        w("- max |F_route1(claim) - F_route2(claim)| = %s" % fmt(df.max(), 2))
        w("")
        d = agg(route2, "block", "err_r2")
        table_from(d, "block")
        w("### route-2 configurations (largest discrepancy first)")
        w("")
        w("| config | p | eps | sigma | err_r2 | err_r1 | dF(claim) |")
        w("|---|---|---|---|---|---|---|")
        for r in sorted(route2, key=lambda r: -float(r["err_r2"]))[:15]:
            w("| %s | %s | %s | %s | %s | %s | %s |"
              % (r["name"], r["p"], r["eps"], r["sigma"], fmt(r["err_r2"], 2),
                 fmt(r["err_r1"], 2), fmt(r["dF_r1_r2_claim"], 2)))
        w("")

    # ---------------- Monte Carlo ----------------------------------------
    if mc:
        w("## 4. Monte-Carlo route (raw simulation)")
        w("")
        w("`mean_dev` = average over seeds of (exact empirical LP minimiser - claim);")
        w("`max|z|` = that deviation divided by its Monte-Carlo standard error;")
        w("`subgrad max|z|` = the population subgradient at the claim divided by its")
        w("MC standard error (this must be O(1) for the claim to hold).")
        w("")
        w("| config | p | n | mean_dev | max\\|z\\| | subgrad max\\|z\\| |")
        w("|---|---|---|---|---|---|")
        for r in mc:
            md = r.get("mean_dev", "")
            try:
                md = np.array(json.loads(md.replace("'", '"')))
                md = "[" + ", ".join("%.4f" % v for v in np.atleast_1d(md)) + "]"
            except Exception:
                pass
            w("| %s | %s | %s | %s | %s | %s |"
              % (r["name"], r["p"], r["n"], md,
                 fmt(r.get("max_abs_z"), 2) if r.get("max_abs_z") else "-",
                 fmt(r.get("max_abs_grad_z"), 2) if r.get("max_abs_grad_z") else "-"))
        w("")
        gz = [float(r["max_abs_grad_z"]) for r in mc if r.get("max_abs_grad_z")]
        if gz:
            w("largest Monte-Carlo |z| for the population subgradient at the "
              "claimed minimiser: %s (n = 2e6 per component; |z| < 4 is "
              "consistent with 0)" % fmt(max(gz), 2))
            w("")

    # ---------------- uniqueness -----------------------------------------
    if "uniqueness" in summary:
        u = summary["uniqueness"]
        w("## 5. Uniqueness diagnostics")
        w("")
        w("- max negative increment of Xi over a 3e5-point grid on [0,30]: %s"
          % fmt(u.get("max_negative_increment_of_Xi"), 2))
        w("- scalar global grid scans (all error distributions x su x tau x sigma):"
          " %d failures" % len(u.get("scalar_grid_scan_failures", [])))
        w("- line scans through the claim for p=2,3,4 and each of (i),(ii),(iii):"
          " %d violations" % len(u.get("line_scan_violations", [])))
        w("- numeric Hessian at the claim (p=2,3,4): %d non-positive-definite"
          % len(u.get("hessian_not_pd", [])))
        w("")
        if u.get("scalar_grid_scan_failures"):
            w("```")
            for f in u["scalar_grid_scan_failures"][:20]:
                w(str(f))
            w("```")
            w("")

    # ---------------- stress ---------------------------------------------
    if "stress" in summary:
        s = summary["stress"]
        w("## 6. Stress tests of the assumptions")
        w("")
        w("### (a) E[X] != 0 (the claim assumes E[X] = 0) -- route 2")
        w("")
        w("| p | mu | eps | beta_claim | beta_numeric | dev_inf | F(claim)-F(min) |")
        w("|---|---|---|---|---|---|---|")
        for r in s.get("mu_x_nonzero", []):
            w("| %d | %s | %s | %s | %s | %s | %s |"
              % (r["p"], r["mu"], r["eps"],
                 "[" + ",".join("%.4f" % v for v in r["beta_claim"]) + "]",
                 "[" + ",".join("%.4f" % v for v in r["beta_num"]) + "]",
                 fmt(r["dev_inf"]), fmt(r["gap"], 2)))
        w("")
        w("### (b) singular Sigma_x (the claim assumes Sigma_x > 0)")
        w("")
        w("| Su | beta_claim | F along the unidentified direction e2 | spread |")
        w("|---|---|---|---|")
        for r in s.get("Sx_singular", []):
            w("| %s | %s | %s | %s |"
              % (r["Su"], r["beta_claim"],
                 "[" + ", ".join(fmt(v) for v in r["F_along_e2"]) + "]",
                 fmt(r["spread"], 2)))
        w("")
        if "cauchy" in s:
            w("### (c) Cauchy errors (E|eps| = infinity): sample criterion means")
            w("")
            w("`%s` -- the population criterion is +infinity for every beta, so the"
              % s["cauchy"]["sample_means"])
            w("claim's moment assumption E|eps| < infinity is needed for the")
            w("criterion to be well defined (the density assumption is not).")
            w("")
        if "M_indefinite" in s:
            w("### (d) indefinite M: %s" % s["M_indefinite"]["note"])
            w("")

    # ---------------- huge bandwidth --------------------------------------
    if "huge_bandwidth" in summary and "checks" in summary["huge_bandwidth"]:
        w("## 7. Huge bandwidth, 50-digit arithmetic (mpmath)")
        w("")
        w("R_sigma(b) = Xi(sqrt((1-b)^2 + b^2/4 + sigma^2)), scalar model,")
        w("claim bbar = 1/1.25 = 0.8.  R at the claim and the increments when")
        w("moving away from it, in units where the contrast is O(1/sigma).")
        w("")
        w("| sigma | eps | R(claim) | dR(+1e-4) | dR(-1e-4) | dR(+0.5) | dR(-0.5) | curvature |")
        w("|---|---|---|---|---|---|---|---|")
        for r in summary["huge_bandwidth"]["checks"]:
            w("| %g | %s | %s | %s | %s | %s | %s | %s |"
              % (r["sigma"], r["eps"], r["R_at_claim"], r["dR_plus_1e4"],
                 r["dR_minus_1e4"], r["dR_plus_0p5"], r["dR_minus_0p5"],
                 r["curvature"]))
        w("")
        w("(all increments are positive and the curvature is positive at the")
        w("claim, so the claim is still the strict minimiser; the contrast just")
        w("decays like phi(0)/(2*sigma).)")
        w("")

    # ---------------- flat cases ------------------------------------------
    if "flat_cases" in summary and "rows" in summary["flat_cases"]:
        w("## 8. Errors bounded away from 0, 300-digit arithmetic (mpmath)")
        w("")
        w("For eps == 10 and eps = 3 + Exp(1), Xi(s) underflows to 0.0 in double")
        w("precision over a whole ellipsoid of beta, so the double-precision")
        w("optimiser returns an arbitrary point of that ellipsoid.  In 300-digit")
        w("arithmetic the criterion is strictly increasing again and the argmin")
        w("is the claim.")
        w("")
        w("| eps | su | M | sigma | part | beta_claim | hp argmin err | dR(+0.01) | dR(-0.01) | dR in float64 |")
        w("|---|---|---|---|---|---|---|---|---|---|")
        for r in summary["flat_cases"]["rows"]:
            w("| %s | %s | %s | %s | %s | %s | %s | %s | %s | %s |"
              % (r["eps"], r["su"], r["M"], r["sigma"], r["part"],
                 fmt(r["beta_claim"], 6), r["argmin_err"], r["dR_plus_0.01"],
                 r["dR_minus_0.01"], fmt(r["dR_plus_0.01_dp"], 2)))
        w("")

    # ---------------- scalar special cases --------------------------------
    if sweep:
        sp = [r for r in sweep if r["block"] == "scalar_(iii)_M=Su"]
        if sp:
            v = np.array([float(r["err_inf"]) for r in sp])
            w("## 9. The two scalar special cases named in the statement")
            w("")
            w("p = 1, Sigma_x = 1, Sigma_u = sigma_u^2, beta* = 1:")
            w("")
            w("- (ii) claims beta*/(1+sigma_u^2): checked in all scalar (i)/(ii)")
            w("  configurations (that is exactly bbar).")
            w("- (iii) with M = Sigma_u claims beta*/(1+2 sigma_u^2): %d such"
              % len(sp))
            w("  configurations, max err_inf = %s" % fmt(v.max(), 2))
            w("")
            w("| config | beta_claim | beta_numeric | err_inf |")
            w("|---|---|---|---|")
            for r in sorted(sp, key=lambda r: -float(r["err_inf"]))[:8]:
                w("| %s | %s | %s | %s |"
                  % (r["name"], r["beta_claim"][:24], r["beta_num"][:24],
                     fmt(r["err_inf"], 2)))
            w("")

    if "runtime_s" in summary:
        w("---")
        w("")
        w("Total runtime of the generating run: %s s (quick=%s)."
          % (fmt(summary["runtime_s"], 1), summary.get("quick")))
        w("")

    with open(os.path.join(RES, "tables.md"), "w", encoding="utf-8") as f:
        f.write("\n".join(OUT))
    print("wrote", os.path.join(RES, "tables.md"))
    print("\n".join(OUT[:5]))


if __name__ == "__main__":
    main()
